import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowRight, CalendarDays, Car, Check, ChevronRight, CloudSun, Compass, Download, Heart, Hotel, LogIn, MapPin, Menu, Plane, Search, ShieldCheck, Sparkles, Star, Users, Utensils, X } from "lucide-react";
import { destinations, rankDestinations, type SearchProfile } from "@/lib/destinationCatalog";

const interests = ["Strand","Ruhe","Wellness","Kultur","Essen","Natur","Abenteuer","Nightlife","Familie","Luxus"];
const defaultProfile: SearchProfile = { text: "Warm, ruhig, gutes Essen und ein komfortables Hotel", budget: 2200, people: 2, days: 7, maxFlight: 8, interests: ["Ruhe","Essen","Strand"], hotelLevel: "Comfort" };

function money(value:number){ return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value); }
function saveProfile(profile:SearchProfile){ localStorage.setItem("travelmatch-profile",JSON.stringify(profile)); }
function loadProfile(){ try { return JSON.parse(localStorage.getItem("travelmatch-profile")||"") as SearchProfile; } catch { return defaultProfile; } }
function saveFavorite(id:string){ const current=JSON.parse(localStorage.getItem("travelmatch-favorites")||"[]") as string[]; localStorage.setItem("travelmatch-favorites",JSON.stringify(current.includes(id)?current.filter(x=>x!==id):[...current,id])); }
function favorites(){ try{return JSON.parse(localStorage.getItem("travelmatch-favorites")||"[]") as string[];}catch{return [];} }

function Shell({children}:{children:React.ReactNode}){
  const [open,setOpen]=useState(false); const location=useLocation();
  const links=[["/","Home"],["/search","Suche"],["/results","Ergebnisse"],["/planner","Reiseplan"],["/favorites","Favoriten"]];
  useEffect(()=>setOpen(false),[location.pathname]);
  return <div className="min-h-screen bg-[#f6f6f3] text-slate-950">
    <header className="sticky top-0 z-50 border-b border-white/50 bg-white/70 backdrop-blur-2xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
        <Link to="/" className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-950 text-white shadow-xl"><Compass className="h-5 w-5"/></span><div><div className="font-semibold tracking-tight">TravelMatch</div><div className="text-xs text-slate-500">Curated journeys</div></div></Link>
        <nav className="hidden items-center gap-1 md:flex">{links.map(([to,label])=><Link key={to} to={to} className={`rounded-full px-4 py-2 text-sm transition ${location.pathname===to?"bg-slate-950 text-white":"text-slate-600 hover:bg-white"}`}>{label}</Link>)}<Link to="/account" className="ml-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm">Konto</Link></nav>
        <button className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
      </div>
      {open&&<div className="border-t bg-white px-5 py-4 md:hidden">{links.map(([to,label])=><Link key={to} to={to} className="block rounded-xl px-3 py-3 text-sm">{label}</Link>)}</div>}
    </header>{children}
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 md:grid-cols-3 lg:px-8"><div><div className="font-semibold">TravelMatch</div><p className="mt-2 text-sm text-slate-500">Premium-Reiseplanung mit transparenten Empfehlungen.</p></div><div className="text-sm text-slate-500">Flüge · Hotels · Wetter · Visa · Mietwagen</div><div className="text-sm text-slate-500 md:text-right">Live-Anbindungen werden über sichere API-Schnittstellen aktiviert.</div></div></footer>
  </div>;
}

const Glass=({children,className=""}:{children:React.ReactNode,className?:string})=><div className={`rounded-[2rem] border border-white/80 bg-white/75 shadow-[0_24px_80px_rgba(15,23,42,.08)] backdrop-blur-2xl ${className}`}>{children}</div>;

export function HomePage(){
  return <Shell><main>
    <section className="relative overflow-hidden px-5 py-12 lg:px-8 lg:py-20"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(196,181,253,.4),transparent_28%),radial-gradient(circle_at_20%_40%,rgba(125,211,252,.28),transparent_30%)]"/><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
      <div><div className="inline-flex items-center gap-2 rounded-full border border-white bg-white/70 px-4 py-2 text-sm shadow-sm"><Sparkles className="h-4 w-4"/> Reiseplanung, die sich wie ein Concierge anfühlt</div><h1 className="mt-7 max-w-4xl text-5xl font-semibold tracking-[-.055em] sm:text-6xl lg:text-7xl">Dein Urlaub. Durchdacht bis ins Detail.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Beschreibe deine Wünsche. TravelMatch bewertet über 100 Ziele, gleicht Budget, Flugzeit, Hotelstandard und Interessen ab und erklärt dir die besten Optionen verständlich.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/search" className="inline-flex items-center gap-2 rounded-full bg-slate-950 px-6 py-3.5 font-medium text-white shadow-xl">Reise finden <ArrowRight className="h-4 w-4"/></Link><Link to="/results" className="rounded-full border border-slate-200 bg-white px-6 py-3.5 font-medium">Beispiele ansehen</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-500"><span>110 Reiseziele</span><span>Budget-Matching</span><span>Mehrseitiger Flow</span></div></div>
      <Glass className="overflow-hidden p-3"><img className="h-[440px] w-full rounded-[1.6rem] object-cover" src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1500&q=88" alt="Premium travel"/><div className="grid gap-3 p-3 sm:grid-cols-3"><Mini icon={Plane} text="Flugvergleich"/><Mini icon={Hotel} text="Hotel-Match"/><Mini icon={CloudSun} text="Live-Wetter"/></div></Glass>
    </div></section>
    <section className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="grid gap-4 md:grid-cols-3">{[[Search,"Intelligent suchen","Freitext, Interessen, Budget, Personen, Datum und maximale Flugzeit."],[Sparkles,"Empfehlungen verstehen","Jede Empfehlung zeigt Score, Preis und konkrete Gründe."],[CalendarDays,"Urlaub komplett planen","Flug, Hotel, Aktivitäten, Restaurants, Tagesplan, Packliste und PDF."]].map(([Icon,title,text]:any)=><Glass key={title} className="p-6"><Icon className="h-6 w-6"/><h2 className="mt-8 text-xl font-semibold">{title}</h2><p className="mt-2 leading-7 text-slate-500">{text}</p></Glass>)}</div></section>
  </main></Shell>;
}
function Mini({icon:Icon,text}:{icon:any,text:string}){return <div className="rounded-2xl bg-slate-50 p-4"><Icon className="h-5 w-5"/><div className="mt-2 text-sm font-medium">{text}</div></div>}

export function SearchPage(){
  const navigate=useNavigate(); const [profile,setProfile]=useState<SearchProfile>(loadProfile());
  const toggle=(x:string)=>setProfile(p=>({...p,interests:p.interests.includes(x)?p.interests.filter(i=>i!==x):[...p.interests,x]}));
  const submit=()=>{saveProfile(profile);navigate("/results");};
  return <Shell><main className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="mb-8"><div className="text-sm text-slate-500">Schritt 1 von 3</div><h1 className="mt-2 text-4xl font-semibold tracking-tight">Was soll dein Urlaub können?</h1></div><div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
    <Glass className="p-6 sm:p-8"><label className="text-sm font-medium">Beschreibe deinen Wunschurlaub</label><textarea value={profile.text} onChange={e=>setProfile({...profile,text:e.target.value})} className="mt-3 min-h-36 w-full rounded-3xl border border-slate-200 bg-white p-5 text-lg outline-none focus:ring-2 focus:ring-slate-900"/><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Budget (€)" value={profile.budget} onChange={v=>setProfile({...profile,budget:+v})}/><Field label="Personen" value={profile.people} onChange={v=>setProfile({...profile,people:+v})}/><Field label="Reisedauer (Tage)" value={profile.days} onChange={v=>setProfile({...profile,days:+v})}/><Field label="Max. Flugzeit (Std.)" value={profile.maxFlight} onChange={v=>setProfile({...profile,maxFlight:+v})}/></div><div className="mt-7"><div className="text-sm font-medium">Interessen</div><div className="mt-3 flex flex-wrap gap-2">{interests.map(x=><button key={x} onClick={()=>toggle(x)} className={`rounded-full border px-4 py-2 text-sm transition ${profile.interests.includes(x)?"border-slate-950 bg-slate-950 text-white":"border-slate-200 bg-white"}`}>{x}</button>)}</div></div><div className="mt-7"><div className="text-sm font-medium">Hotelstandard</div><div className="mt-3 grid grid-cols-3 gap-2">{(["Smart","Comfort","Premium"] as const).map(x=><button key={x} onClick={()=>setProfile({...profile,hotelLevel:x})} className={`rounded-2xl border p-4 text-sm ${profile.hotelLevel===x?"border-slate-950 bg-slate-950 text-white":"border-slate-200 bg-white"}`}>{x}</button>)}</div></div><button onClick={submit} className="mt-8 flex w-full items-center justify-center gap-2 rounded-full bg-slate-950 px-6 py-4 font-medium text-white">Passende Reisen finden <ArrowRight className="h-4 w-4"/></button></Glass>
    <div className="space-y-4"><Glass className="p-6"><div className="flex items-center gap-3"><Sparkles/><div><div className="font-semibold">KI-Reiseberater</div><div className="text-sm text-slate-500">Analysiert Wünsche und Prioritäten.</div></div></div><div className="mt-6 space-y-3 text-sm text-slate-600">{["Budget und Preis-Leistung","Ruhe, Komfort und Interessen","Flugzeit und Reisedauer","passende Hotelkategorie"].map(x=><div className="flex gap-2" key={x}><Check className="h-4 w-4"/>{x}</div>)}</div></Glass><Glass className="p-6"><div className="text-3xl font-semibold">{destinations.length}</div><div className="mt-1 text-sm text-slate-500">Reiseziele im aktuellen Katalog</div></Glass></div>
  </div></main></Shell>;
}
function Field({label,value,onChange}:{label:string,value:number,onChange:(v:string)=>void}){return <label><span className="text-sm font-medium">{label}</span><input type="number" value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-slate-900"/></label>}

export function ResultsPage(){
  const profile=loadProfile(); const results=useMemo(()=>rankDestinations(profile).slice(0,24),[profile]);
  return <Shell><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-sm text-slate-500">Schritt 2 von 3</div><h1 className="mt-2 text-4xl font-semibold tracking-tight">Deine besten Matches</h1><p className="mt-2 text-slate-500">Sortiert nach Passung, Gesamtpreis und Flugzeit.</p></div><Link to="/search" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm">Suche anpassen</Link></div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{results.map((d,index)=><Glass key={d.id} className="group overflow-hidden"><div className="relative"><img src={d.image} className="h-56 w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-sm font-semibold backdrop-blur">#{index+1} · {d.score}% Match</div><button onClick={()=>saveFavorite(d.id)} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white/90"><Heart className="h-4 w-4"/></button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{d.name}</h2><p className="text-sm text-slate-500">{d.country} · {d.flightHours.toFixed(1)} Std.</p></div><div className="text-right"><div className="font-semibold">{money(d.total)}</div><div className="text-xs text-slate-500">gesamt geschätzt</div></div></div><div className="mt-4 flex flex-wrap gap-2">{d.themes.map(t=><span key={t} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{t}</span>)}</div><p className="mt-4 text-sm leading-6 text-slate-600">{d.reasons.join(" · ")}</p><Link to={`/destination/${d.id}`} className="mt-5 flex items-center justify-between rounded-2xl bg-slate-950 px-4 py-3 text-sm text-white">Details ansehen <ChevronRight className="h-4 w-4"/></Link></div></Glass>)}</div></main></Shell>;
}

export function DestinationPage(){
  const {id}=useParams(); const profile=loadProfile(); const result=rankDestinations(profile).find(x=>x.id===id)||rankDestinations(profile)[0];
  const live=[[Plane,"Flug","Amadeus / Skyscanner API-ready"],[Hotel,"Hotel","Live-Hotelpreise API-ready"],[CloudSun,"Wetter","Wetterdienst API-ready"],[ShieldCheck,"Visa & Einreise","Regelwerk API-ready"],[Car,"Mietwagen","Provider-Schnittstelle vorbereitet"]];
  return <Shell><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><img src={result.image} className="h-[460px] w-full rounded-[2.2rem] object-cover shadow-2xl"/><div className="mt-7"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-slate-950 px-4 py-2 text-sm text-white">{result.score}% Match</span><span className="text-sm text-slate-500">{result.region}</span></div><h1 className="mt-4 text-5xl font-semibold tracking-tight">{result.name}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">Dieses Ziel passt besonders gut, weil {result.reasons.join(", ")}.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{live.map(([Icon,title,text]:any)=><Glass key={title} className="p-5"><Icon className="h-5 w-5"/><div className="mt-4 font-semibold">{title}</div><div className="mt-1 text-sm text-slate-500">{text}</div></Glass>)}</div></div><div className="space-y-5"><Glass className="p-6"><div className="text-sm text-slate-500">Geschätzter Gesamtpreis</div><div className="mt-2 text-4xl font-semibold">{money(result.total)}</div><div className="mt-6 space-y-3 text-sm"><Price label="Flüge" value={result.flight}/><Price label={`${profile.days} Nächte · ${profile.hotelLevel}`} value={result.hotel}/><Price label="Gesamt" value={result.total} strong/></div><Link to="/planner" className="mt-6 flex items-center justify-center gap-2 rounded-full bg-slate-950 px-5 py-4 text-white">Reiseplan erstellen <ArrowRight className="h-4 w-4"/></Link><button onClick={()=>saveFavorite(result.id)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-4"><Heart className="h-4 w-4"/> Favorit speichern</button></Glass><Glass className="p-6"><div className="font-semibold">Warum dieses Ziel?</div><div className="mt-4 space-y-3">{result.reasons.map(r=><div className="flex gap-3 text-sm text-slate-600" key={r}><Star className="h-4 w-4 shrink-0"/>{r}</div>)}</div></Glass></div></div></main></Shell>;
}
function Price({label,value,strong=false}:{label:string,value:number,strong?:boolean}){return <div className={`flex justify-between ${strong?"border-t pt-3 font-semibold":"text-slate-600"}`}><span>{label}</span><span>{money(value)}</span></div>}

export function PlannerPage(){const profile=loadProfile();const top=rankDestinations(profile)[0];const days=Array.from({length:Math.min(profile.days,7)},(_,i)=>i+1);return <Shell><main className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-sm text-slate-500">Schritt 3 von 3</div><h1 className="mt-2 text-4xl font-semibold">Dein Reiseplan für {top.name}</h1></div><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-full bg-slate-950 px-5 py-3 text-white"><Download className="h-4 w-4"/> Als PDF</button></div><div className="mt-8 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4">{[[Plane,"Flug",`${top.flightHours.toFixed(1)} Std. · ${money(top.flight)}`],[Hotel,"Hotel",`${profile.hotelLevel} · ${money(top.hotel)}`],[Utensils,"Restaurants","Lokale Favoriten und reservierbare Optionen"],[Car,"Mietwagen","Vergleich am Zielort"]].map(([Icon,title,text]:any)=><Glass key={title} className="p-5"><Icon/><div className="mt-4 font-semibold">{title}</div><div className="mt-1 text-sm text-slate-500">{text}</div></Glass>)}</div><Glass className="p-6"><h2 className="text-xl font-semibold">Tagesplan</h2><div className="mt-5 space-y-4">{days.map(day=><div key={day} className="rounded-2xl bg-slate-50 p-5"><div className="text-sm font-semibold">Tag {day}</div><div className="mt-2 text-sm leading-6 text-slate-600">Entspanntes Frühstück · ausgewählte Aktivität · Restaurantempfehlung · flexible Freizeit</div></div>)}</div><div className="mt-6 rounded-2xl border border-slate-200 p-5"><div className="font-semibold">Packliste</div><div className="mt-3 grid grid-cols-2 gap-2 text-sm text-slate-600">{["Ausweis","Badesachen","Sonnenschutz","Ladegeräte","Medikamente","Reiseunterlagen"].map(x=><div key={x}>□ {x}</div>)}</div></div></Glass></div></main></Shell>}

export function FavoritesPage(){const [ids,setIds]=useState<string[]>([]);useEffect(()=>setIds(favorites()),[]);const list=destinations.filter(d=>ids.includes(d.id));return <Shell><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><h1 className="text-4xl font-semibold">Favoriten</h1><p className="mt-2 text-slate-500">Deine gespeicherten Reiseziele.</p>{list.length?<div className="mt-8 grid gap-5 md:grid-cols-3">{list.map(d=><Link key={d.id} to={`/destination/${d.id}`}><Glass className="overflow-hidden"><img src={d.image} className="h-48 w-full object-cover"/><div className="p-5 font-semibold">{d.name}</div></Glass></Link>)}</div>:<Glass className="mt-8 p-10 text-center"><Heart className="mx-auto"/><div className="mt-4 font-semibold">Noch keine Favoriten</div><Link to="/results" className="mt-5 inline-block rounded-full bg-slate-950 px-5 py-3 text-white">Ziele entdecken</Link></Glass>}</main></Shell>}

export function AccountPage(){return <Shell><main className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><Glass className="p-8"><LogIn className="h-7 w-7"/><h1 className="mt-8 text-4xl font-semibold">Dein TravelMatch-Konto</h1><p className="mt-4 leading-7 text-slate-500">Login, Favoriten, Reiseverlauf und gespeicherte Reisen werden hier über Supabase verbunden.</p><button className="mt-8 w-full rounded-full bg-slate-950 px-5 py-4 text-white">Mit E-Mail anmelden</button></Glass><Glass className="p-8"><div className="font-semibold">Supabase-Funktionen</div><div className="mt-6 space-y-4">{["Sicherer Login","Favoriten synchronisieren","Reiseverlauf speichern","Reisepläne geräteübergreifend öffnen"].map(x=><div className="flex gap-3 text-slate-600" key={x}><Check className="h-5 w-5"/>{x}</div>)}</div></Glass></div></main></Shell>}
